# Generated by Django 4.1 on 2022-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccounter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(verbose_name='Calories per 100g'),
        ),
    ]
