# Generated by Django 4.1 on 2022-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccounter_app', '0002_alter_category_options_alter_meal_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='carbohydrates_percent',
            new_name='carbohydrates',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='cholesterol_percent',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='fat_percent',
            new_name='proteins',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fiber_percent',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein_percent',
        ),
    ]
